---
  - name: "Ciphertrust Manager Role"
    hosts: localhost
    connection: local 

    vars_files:
      - variables.yaml

    tasks:
    - name: "Create new cluster"
      thales.ciphertrust.cm_cluster_new: 
        localNode: "{{ this_node_connection_string }}"
      register: payload

    - name: Debug Output
      debug: var=payload

