---
  - name: "Create and join Ciphertrust Manager Role"
    hosts: localhost
    connection: local 

    vars_files:
      - variables.yaml

    tasks:

    - name: "Create new key on Ciphertrust Manager"
      thales.ciphertrust.vault_keys_create:
        localNode: "{{ this_node_connection_string }}"
        keyName: "AnsibleKey"
      register: output

    - name: Debug Output
      debug: var=output

