---
  - name: "Delete DPG Stuff Playbook"
    hosts: localhost
    connection: local

    vars_files:
      - variables.yaml

    tasks:

    - name: "Delete DPG Client Profile"
      thales.ciphertrust.dpg_client_profile_delete:
        localNode: "{{ this_node_connection_string }}"
        names: 
          - "{{ client_profile_name }}"
    - name: "Delete DPG Policy"
      thales.ciphertrust.dpg_policies_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - "{{ dpg_policy_name }}"

    - name: "Delete Access Policies"
      thales.ciphertrust.dpg_access_policy_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - "{{ access_policy_name }}"

    - name: "Delete User Sets"
      thales.ciphertrust.dpg_user_sets_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - AnsibleUserset101
          - AnsibleUserset102

    - name: "Delete Users"
      thales.ciphertrust.cm_usermgmt_user_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - AnsibleUser1
          - AnsibleUser2

    - name: "Delete Protection Profiles"
      thales.ciphertrust.dpg_protection_policy_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - "{{ non_card_protection_policy_name }}"
          - "{{ fpe_card_protection_policy_name }}"
      register: output

    - name: "Delete Character Sets"
      thales.ciphertrust.dpg_character_sets_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - "{{ char_set_name }}"

    - name: "Delete NAE Interface"
      thales.ciphertrust.config_interface_nae_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - "nae_all_{{ nae_port_number }}"

    - name: "Delete Keys"
      thales.ciphertrust.vault_keys_delete:
        localNode: "{{ this_node_connection_string }}"
        names:
          - "{{ dpg_key_name }}"

    - name: Debug Output
      debug: var=output
