---
  - name: "Sample playbook for Group and User Management on CipherTrust Manager"
    hosts: localhost
    connection: local

    vars_files:
      - vars/userMgmt.yml

    tasks:
    - name: "Create new user"
      thales.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "create"
        username: "john.doe"
        password: "cmPassw0rd!"
        email: "john.doe@example.com"
        name: "John Doe"

    - name: "Update user info"
      thales.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "patch"
        cm_user_id: "local|6c045e48-7e2e-4b01-ac88-6d2a13d8dc95"
        username: "john.doe"
        email: "aj@example.com"
        name: "Anurag Jain"

    - name: "Change user password"
      thales.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "changepw"
        username: "john.doe"
        password: "cmPassw0rd3!"
        new_password: "cmPassw0rd4!"

    - name: "Update self"
      thales.ciphertrust.usermgmt_users_save:
        localNode: "{{ this_node_connection_string }}"
        op_type: "patch_self"
        name: "CM Admin"